### ISSUE TITLE
Update for Big Sur?

### ISSUE THREAD

**Issue by chrisspiegl** [stirtingale/Alfred---Toggle-Function-Keys-On-Of#1]
I just tried this and it does not seem to work on Big Sur?
Can this be updated easily?
Would appreciate it 🌸.

**Comment by stirtingale** [comment]
@chrisspiegl 

Hey - I honestly completely forgot about this being public.

I actually got so annoyed with the basic Apple keyboard I went back to a mechanical one with OSX / media key support

However ... I still use the script as sometimes the system pause/play gets confused if you have media in focus in browser (e.g. I am Chrome with the video paused, Spotify playing in the background, want to quickly pause, hit OSX Media Pause, and it then reads that as play the video in Chrome)

Anyway --

I have added the most recent workflow - this isn't mine; I can't remember where I found it so can't give proper credit

https://github.com/stirtingale/Alfred---Toggle-Function-Keys-On-Of/blob/master/Vintage%20Media%20Keys.alfredworkflow

I have that configured to just fire the play/pause script on APPLE`+OPTION+S

![Screenshot 2021-02-22 at 13 30 22](https://user-images.githubusercontent.com/25981099/108715003-2d038a80-7512-11eb-8c6b-a71feab1c34b.png)

The script it triggers is

```
-- Define apps in order you want them to respond
if application "iTunes" is running then
  tell application "iTunes"
    playpause
    return "itunes"
  end tell
end if

if application "Spotify" is running then
  tell application "Spotify"
    playpause
    return "spotify"
  end tell
end if
```

... and that seems to work on every OS version

![Screenshot 2021-02-22 at 13 31 00](https://user-images.githubusercontent.com/25981099/108715031-37258900-7512-11eb-8cda-d67b6621a98f.png)

**Comment by chrisspiegl** [comment]
Interesting workaround. I am actually specifically looking for the switch from Function Keys to Media Keys.
I usually use the Brightness, Volume and Media Control, but for Live Streaming I would like to use the F1 - F12 for hotkeys to switch between cameras and stuff.
That's why I was excited about this.
But I understand if it's not something to be updated.
Cheers 🌸.

**Comment by stirtingale** [comment]
My bad -- didn't think that fully through

This script itself is 

> on alfred_script(q)
> tell application "System Preferences"
>     reveal anchor "keyboardTab" of pane "com.apple.preference.keyboard"
> end tell
> tell application "System Events" to tell process "System Preferences"
>     click checkbox 1 of tab group 1 of window 1
> end tell
> quit application "System Preferences"
> end alfred_script

I am not running Big Sur on my dev machine (which I am not now) so I will get back to you when I am at my other machine which is running it. 

My assumption is the media toggle box has changed location. So to get it work again you just need to update the click `checkbox 1 of tab group 1 of window 1` bit of the code. It will be a different tab or location

Then it should work again 

---

If you are feeling fancy you could always have a dedicated programmable pad like @ https://www.instructables.com/Making-a-powerful-programmable-keypad-for-less-tha/

You can use Keyboard Maestro instead of HID macro in Windows

**Comment by jaime-gacitua** [comment]
Hey I got the fix for Monterey @chrisspiegl

change

`checkbox 1 of tab group 1 of window 1`

to this

`checkbox 3 of tab group 1 of window 1`

I don't know how to make a pull request against the code within the workflow file.

Perhaps update @stirtingale

**Comment by Te0SX** [comment]
Opened a pull request for the changes, I added one delay as well since you had to run the toggle twice to work properly. For Ventura new changes will be probably needed for the scripts, but for now it is fine.

https://github.com/stirtingale/Alfred---Toggle-Function-Keys-On-Of/pull/2

**Comment by stirtingale** [comment]
@Te0SX 

Thanks! I will accept the PR

I will re-add the previous version for Big Sur users ( it breaks it for Big Sur ) so they have access to it if they are not on Monterey.

I think going forward I might restructure it have a version specific file to keep it working for everyone
